# Generated by Django 6.0.4 on 2026-05-07 17:05

import django.utils.timezone
import recrutement.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=recrutement.models.generer_reference, editable=False, max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('nationalite', models.CharField(choices=[("Côte d'Ivoire", "Côte d'Ivoire"), ('Burkina Faso', 'Burkina Faso'), ('Mali', 'Mali'), ('Sénégal', 'Sénégal'), ('Ghana', 'Ghana'), ('Autre', 'Autre')], max_length=50)),
                ('poste', models.CharField(choices=[('GK', 'Gardien'), ('DC', 'Déf. Central'), ('LAT', 'Latéral'), ('MD', 'Milieu Déf.'), ('MO', 'Milieu Off.'), ('AIL', 'Ailier'), ('ATT', 'Attaquant'), ('OTH', 'Autre')], max_length=3)),
                ('numero_prefere', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('pied_fort', models.CharField(choices=[('Droit', 'Droit'), ('Gauche', 'Gauche'), ('Ambidextre', 'Ambidextre')], max_length=12)),
                ('ancien_club', models.CharField(blank=True, max_length=100)),
                ('telephone_whatsapp', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('adresse', models.CharField(blank=True, max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='candidatures/')),
                ('statut', models.CharField(choices=[('pending', 'En attente'), ('waiting', 'Mise en attente'), ('accepted', 'Acceptée'), ('refused', 'Refusée')], default='pending', max_length=10)),
                ('date_soumission', models.DateTimeField(default=django.utils.timezone.now)),
                ('note_interne', models.TextField(blank=True)),
                ('notifie', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Candidature',
                'verbose_name_plural': 'Candidatures',
                'ordering': ['-date_soumission'],
            },
        ),
    ]
