# Generated by Django 6.0.5 on 2026-06-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='categorie',
            field=models.CharField(choices=[('U10', 'U10'), ('U12', 'U12'), ('U13', 'U13'), ('U15', 'U15'), ('U17+', 'U17+')], default='U13', max_length=4),
        ),
        migrations.AddField(
            model_name='candidature',
            name='contact_urgence',
            field=models.CharField(blank=True, max_length=150, verbose_name="Contact d'urgence (nom & téléphone)"),
        ),
        migrations.AddField(
            model_name='candidature',
            name='email_parent',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email du parent/tuteur'),
        ),
        migrations.AddField(
            model_name='candidature',
            name='info_scolaire',
            field=models.CharField(blank=True, max_length=200, verbose_name='École / Établissement'),
        ),
        migrations.AddField(
            model_name='candidature',
            name='nom_parent',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nom du parent/tuteur'),
        ),
        migrations.AddField(
            model_name='candidature',
            name='pdf_inscription',
            field=models.FileField(blank=True, null=True, upload_to='inscriptions_pdf/'),
        ),
        migrations.AddField(
            model_name='candidature',
            name='sexe',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='candidature',
            name='telephone_parent',
            field=models.CharField(blank=True, max_length=30, verbose_name='Téléphone du parent/tuteur'),
        ),
    ]
