# Generated by Django 6.0.5 on 2026-06-04 16:42

import django.db.models.deletion
import django.utils.timezone
import payments.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recrutement', '0002_candidature_categorie_candidature_contact_urgence_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComptePaiement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('wave', 'Wave'), ('orange_money', 'Orange Money'), ('moov', 'Moov'), ('mtn', 'MTN'), ('virement', 'Virement'), ('espece', 'Espèce')], max_length=20, verbose_name='Mode de paiement')),
                ('numero', models.CharField(max_length=100, verbose_name='Numéro / référence')),
                ('nom_titulaire', models.CharField(max_length=160, verbose_name='Nom du titulaire')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to=payments.models.upload_qr_code, verbose_name='QR code')),
                ('instructions', models.TextField(blank=True, default='', verbose_name='Instructions')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Compte actif')),
                ('ordre_affichage', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Compte de paiement',
                'verbose_name_plural': 'Comptes de paiement',
                'ordering': ['ordre_affichage', 'mode', 'nom_titulaire'],
            },
        ),
        migrations.CreateModel(
            name='PaiementInscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('montant', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Montant (FCFA)')),
                ('capture_depot', models.ImageField(upload_to=payments.models.upload_capture_inscription, verbose_name="Capture d'écran du dépôt")),
                ('statut_validation', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Validé'), ('rejected', 'Refusé')], db_index=True, default='pending', max_length=20, verbose_name='Statut')),
                ('date_paiement', models.DateField(default=django.utils.timezone.localdate, verbose_name='Date du paiement')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes internes')),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('candidature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements_inscription', to='recrutement.candidature', verbose_name='Candidature')),
                ('compte_paiement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_inscription', to='payments.comptepaiement', verbose_name='Numéro utilisé pour le dépôt')),
                ('enregistre_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscriptions_enregistrees', to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscriptions_validees', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
            ],
            options={
                'verbose_name': 'Paiement inscription',
                'verbose_name_plural': 'Paiements inscription',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['statut_validation'], name='idx_inscription_statut'), models.Index(fields=['candidature'], name='idx_inscription_cand')],
            },
        ),
        migrations.CreateModel(
            name='PaiementVisiteMedicale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('montant', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Montant (FCFA)')),
                ('capture_depot', models.ImageField(upload_to=payments.models.upload_capture_visite, verbose_name="Capture d'écran du dépôt")),
                ('statut_validation', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Validé'), ('rejected', 'Refusé')], db_index=True, default='pending', max_length=20, verbose_name='Statut')),
                ('date_paiement', models.DateField(default=django.utils.timezone.localdate, verbose_name='Date du paiement')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes internes')),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('candidature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements_visite_medicale', to='recrutement.candidature', verbose_name='Candidature')),
                ('compte_paiement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_visite', to='payments.comptepaiement', verbose_name='Numéro utilisé pour le dépôt')),
                ('enregistre_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visites_enregistrees', to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visites_validees', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
            ],
            options={
                'verbose_name': 'Paiement visite médicale',
                'verbose_name_plural': 'Paiements visites médicales',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['statut_validation'], name='idx_visite_statut'), models.Index(fields=['candidature'], name='idx_visite_cand')],
            },
        ),
    ]
