# Generated by Django 6.0.5 on 2026-06-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiementinscription',
            name='reference_transaction',
            field=models.CharField(blank=True, default='', help_text="Référence/ID visible sur la capture d'écran du dépôt", max_length=120, verbose_name='Référence de transaction'),
        ),
        migrations.AddField(
            model_name='paiementvisitemedicale',
            name='reference_transaction',
            field=models.CharField(blank=True, default='', help_text="Référence/ID visible sur la capture d'écran du dépôt", max_length=120, verbose_name='Référence de transaction'),
        ),
    ]
