# Generated by Django 6.0.5 on 2026-06-04 17:24

import django.db.models.deletion
import django.utils.timezone
import payments.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('effectif', '0003_joueur_adresse_joueur_ancien_club_and_more'),
        ('payments', '0002_add_reference_transaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CotisationAnnuelle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('annee', models.PositiveIntegerField(db_index=True, verbose_name='Année')),
                ('montant_total', models.DecimalField(decimal_places=0, default=Decimal('1000000'), max_digits=12, verbose_name='Montant total (FCFA)')),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('solde', 'Soldé'), ('en_retard', 'En retard'), ('suspendu', 'Suspendu')], db_index=True, default='en_cours', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('joueur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotisations_annuelles', to='effectif.joueur', verbose_name='Joueur')),
            ],
            options={
                'verbose_name': 'Cotisation annuelle',
                'verbose_name_plural': 'Cotisations annuelles',
                'ordering': ['-annee', 'joueur__nom', 'joueur__prenom'],
            },
        ),
        migrations.CreateModel(
            name='VersementCotisation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_versement', models.CharField(choices=[('premier', '1er versement'), ('mensuel', 'Versement mensuel'), ('rattrapage', 'Rattrapage')], default='mensuel', max_length=20, verbose_name='Type')),
                ('montant', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Montant (FCFA)')),
                ('reference_transaction', models.CharField(blank=True, default='', max_length=120, verbose_name='Référence de transaction')),
                ('capture_depot', models.ImageField(blank=True, null=True, upload_to=payments.models.upload_capture_versement, verbose_name="Capture d'écran du dépôt")),
                ('statut_validation', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Validé'), ('rejected', 'Refusé')], db_index=True, default='pending', max_length=20, verbose_name='Statut')),
                ('date_versement', models.DateField(default=django.utils.timezone.localdate, verbose_name='Date du versement')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('compte_paiement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versements_cotisation', to='payments.comptepaiement', verbose_name='Numéro utilisé pour le dépôt')),
                ('cotisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versements', to='payments.cotisationannuelle', verbose_name='Cotisation')),
                ('enregistre_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versements_enregistres', to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versements_valides', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
            ],
            options={
                'verbose_name': 'Versement cotisation',
                'verbose_name_plural': 'Versements cotisations',
                'ordering': ['-date_versement', '-date_creation'],
            },
        ),
        migrations.AddIndex(
            model_name='cotisationannuelle',
            index=models.Index(fields=['annee'], name='idx_cotisation_annee'),
        ),
        migrations.AddIndex(
            model_name='cotisationannuelle',
            index=models.Index(fields=['statut'], name='idx_cotisation_statut'),
        ),
        migrations.AddConstraint(
            model_name='cotisationannuelle',
            constraint=models.UniqueConstraint(fields=('joueur', 'annee'), name='uq_cotisation_joueur_annee'),
        ),
        migrations.AddIndex(
            model_name='versementcotisation',
            index=models.Index(fields=['statut_validation'], name='idx_versement_statut'),
        ),
        migrations.AddIndex(
            model_name='versementcotisation',
            index=models.Index(fields=['cotisation', 'statut_validation'], name='idx_versement_cot_statut'),
        ),
    ]
