# Generated by Django 6.0.5 on 2026-06-04 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_cotisation_annuelle'),
    ]

    operations = [
        migrations.AddField(
            model_name='versementcotisation',
            name='source_inscription',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versement_cotisation', to='payments.paiementinscription', verbose_name='Paiement inscription source'),
        ),
    ]
