# Generated by Django 6.0.5 on 2026-06-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_source_inscription_et_auto_versement'),
    ]

    operations = [
        migrations.AddField(
            model_name='comptepaiement',
            name='lien',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Lien de paiement'),
        ),
    ]
