# Generated by Django 6.0.5 on 2026-06-08 17:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_add_lien_to_compte_paiement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotisationannuelle',
            name='montant_total',
            field=models.DecimalField(decimal_places=0, default=Decimal('1200000'), max_digits=12, verbose_name='Montant total (FCFA)'),
        ),
    ]
