# Generated by Django 6.0.4 on 2026-05-07 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Joueur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('numero', models.PositiveSmallIntegerField()),
                ('poste', models.CharField(choices=[('GK', 'Gardien'), ('DEF', 'Défenseur'), ('MIL', 'Milieu'), ('ATT', 'Attaquant')], max_length=3)),
                ('age', models.PositiveSmallIntegerField()),
                ('matchs_joues', models.PositiveSmallIntegerField(default=0)),
                ('buts', models.PositiveSmallIntegerField(default=0)),
                ('nationalite', models.CharField(default="Côte d'Ivoire", max_length=60)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='effectif/')),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Joueur',
                'verbose_name_plural': 'Joueurs',
                'ordering': ['poste', 'numero'],
            },
        ),
    ]
