# Generated by Django 6.0.5 on 2026-06-01 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('effectif', '0001_initial'),
        ('recrutement', '0002_candidature_categorie_candidature_contact_urgence_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='joueur',
            options={'ordering': ['categorie', 'sexe', 'poste', 'numero'], 'verbose_name': 'Joueur', 'verbose_name_plural': 'Joueurs'},
        ),
        migrations.AddField(
            model_name='joueur',
            name='candidature',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='joueur', to='recrutement.candidature'),
        ),
        migrations.AddField(
            model_name='joueur',
            name='categorie',
            field=models.CharField(choices=[('U10', 'U10'), ('U12', 'U12'), ('U13', 'U13'), ('U15', 'U15'), ('U17+', 'U17+')], default='U13', max_length=4),
        ),
        migrations.AddField(
            model_name='joueur',
            name='date_inscription',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joueur',
            name='numero_licence',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='joueur',
            name='sexe',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default='M', max_length=1),
        ),
    ]
