# Generated by Django 6.0.5 on 2026-06-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('effectif', '0002_alter_joueur_options_joueur_candidature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joueur',
            name='adresse',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='joueur',
            name='ancien_club',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='joueur',
            name='contact_urgence',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='joueur',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joueur',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='joueur',
            name='email_parent',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='joueur',
            name='info_scolaire',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='joueur',
            name='nom_parent',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='joueur',
            name='pied_fort',
            field=models.CharField(blank=True, choices=[('Droit', 'Droit'), ('Gauche', 'Gauche'), ('Ambidextre', 'Ambidextre')], max_length=12),
        ),
        migrations.AddField(
            model_name='joueur',
            name='telephone_parent',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='joueur',
            name='telephone_whatsapp',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='joueur',
            name='age',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='joueur',
            name='nationalite',
            field=models.CharField(choices=[("Côte d'Ivoire", "Côte d'Ivoire"), ('Burkina Faso', 'Burkina Faso'), ('Mali', 'Mali'), ('Sénégal', 'Sénégal'), ('Ghana', 'Ghana'), ('Autre', 'Autre')], default="Côte d'Ivoire", max_length=60),
        ),
        migrations.AlterField(
            model_name='joueur',
            name='poste',
            field=models.CharField(choices=[('GK', 'Gardien'), ('DC', 'Déf. Central'), ('LAT', 'Latéral'), ('MD', 'Milieu Déf.'), ('MO', 'Milieu Off.'), ('AIL', 'Ailier'), ('ATT', 'Attaquant'), ('OTH', 'Autre')], max_length=3),
        ),
    ]
