# Generated by Django 6.0.5 on 2026-05-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoTicker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('score_live', 'Score en direct'), ('score_resultat', 'Résultat'), ('prochain_match', 'Prochain match'), ('annonce', 'Annonce')], max_length=20, verbose_name='Type')),
                ('categorie', models.CharField(blank=True, help_text='Ex : U17, U15, Ligue 1 CI', max_length=30)),
                ('equipe_dom', models.CharField(blank=True, max_length=60, verbose_name='Équipe domicile')),
                ('equipe_ext', models.CharField(blank=True, max_length=60, verbose_name='Équipe extérieur')),
                ('score_dom', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Score dom.')),
                ('score_ext', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Score ext.')),
                ('minute', models.PositiveSmallIntegerField(blank=True, help_text='Minute de jeu (score_live uniquement)', null=True)),
                ('texte', models.CharField(blank=True, help_text='Texte libre pour les types annonce / prochain_match', max_length=200)),
                ('actif', models.BooleanField(default=True)),
                ('ordre', models.PositiveSmallIntegerField(default=0, help_text="Ordre d'affichage (croissant)")),
            ],
            options={
                'verbose_name': 'Info ticker',
                'verbose_name_plural': 'Infos ticker',
                'ordering': ['ordre', 'pk'],
            },
        ),
    ]
