# Generated by Django 6.0.4 on 2026-05-07 17:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('accroche', models.CharField(blank=True, max_length=300)),
                ('contenu', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/')),
                ('categorie', models.CharField(choices=[('academie', 'Académie'), ('club', 'Club'), ('joueur', 'Joueur'), ('match', 'Match'), ('evenement', 'Événement')], default='club', max_length=20)),
                ('date_publication', models.DateTimeField(default=django.utils.timezone.now)),
                ('en_une', models.BooleanField(default=False)),
                ('publie', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legende', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to='galerie/')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('afficher', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='videos/thumbnails/')),
                ('url', models.URLField(blank=True)),
                ('type_video', models.CharField(choices=[('youtube', 'YouTube'), ('vimeo', 'Vimeo'), ('local', 'Fichier local')], default='youtube', max_length=10)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('afficher', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Vidéo',
                'verbose_name_plural': 'Vidéos',
                'ordering': ['-date'],
            },
        ),
    ]
