# Generated by Django 6.0.4 on 2026-05-07 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipe', models.CharField(max_length=100)),
                ('points', models.PositiveSmallIntegerField(default=0)),
                ('matchs_joues', models.PositiveSmallIntegerField(default=0)),
                ('victoires', models.PositiveSmallIntegerField(default=0)),
                ('nuls', models.PositiveSmallIntegerField(default=0)),
                ('defaites', models.PositiveSmallIntegerField(default=0)),
                ('buts_pour', models.PositiveSmallIntegerField(default=0)),
                ('buts_contre', models.PositiveSmallIntegerField(default=0)),
                ('est_cfld', models.BooleanField(default=False)),
                ('saison', models.CharField(default='2025-2026', max_length=20)),
            ],
            options={
                'verbose_name': 'Classement',
                'verbose_name_plural': 'Classements',
                'ordering': ['-points', '-buts_pour'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipe_domicile', models.CharField(max_length=100)),
                ('equipe_exterieur', models.CharField(max_length=100)),
                ('est_domicile', models.BooleanField(default=True, help_text='CFLD joue à domicile ?')),
                ('score_domicile', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('score_exterieur', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('date', models.DateTimeField()),
                ('lieu', models.CharField(blank=True, max_length=150)),
                ('competition', models.CharField(default='Ligue 1 CI', max_length=100)),
                ('journee', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('type_match', models.CharField(choices=[('a_venir', 'À venir'), ('resultat', 'Résultat')], default='a_venir', max_length=10)),
                ('billet_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matchs',
                'ordering': ['date'],
            },
        ),
    ]
