# Generated by Django 6.0.5 on 2026-06-01 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SEOPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.CharField(help_text='Identifiant unique de la page (ex: accueil, club, academie…)', max_length=80, unique=True)),
                ('titre_seo', models.CharField(blank=True, help_text='Titre affiché dans Google (max 70 car.)', max_length=70)),
                ('meta_description', models.CharField(blank=True, help_text='Description dans les résultats Google (max 160 car.)', max_length=160)),
                ('mots_cles', models.CharField(blank=True, help_text='Mots-clés séparés par des virgules', max_length=300)),
                ('image_sociale', models.ImageField(blank=True, help_text='Image Open Graph / Twitter Card (1200×630 px)', null=True, upload_to='seo/og_images/')),
                ('indexation', models.CharField(choices=[('index, follow', 'Indexer (recommandé)'), ('noindex, nofollow', 'Ne pas indexer'), ('index, nofollow', 'Indexer sans suivre les liens'), ('noindex, follow', 'Ne pas indexer, suivre les liens')], default='index, follow', max_length=30)),
                ('slug_personnalise', models.CharField(blank=True, help_text="Laisser vide pour utiliser l'URL par défaut", max_length=100)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page SEO',
                'verbose_name_plural': 'Pages SEO',
                'ordering': ['page_id'],
            },
        ),
    ]
